/** Travel conversation prompts. Warm, specific to being on a trip together. */
export const promptDeck = [
  { id: "prompt-01", text: "如果這趟旅行可以多留一天，你最想把那一天花在哪裡？" },
  { id: "prompt-02", text: "到目前為止，哪一餐讓你一直記著？是味道、人，還是當時的光？" },
  { id: "prompt-03", text: "旅途中你偷偷留意過誰的哪一個瞬間？說出來給大家聽。" },
  { id: "prompt-04", text: "如果要用一種零食形容這趟旅行，你會選什麼？為什麼？" },
  { id: "prompt-05", text: "誰做過一個很小的決定，讓今天變得比較好？" },
  { id: "prompt-06", text: "這趟旅行裡，你最感謝自己有帶上的東西是什麼？" },
  { id: "prompt-07", text: "如果今晚要寫一張明信片，你會寄給誰？第一句想寫什麼？" },
  { id: "prompt-08", text: "路上有哪個聲音、味道或光線，你想帶回家？" },
  { id: "prompt-09", text: "如果可以重走今天的某一段，你會把哪一段放得更慢？" },
  { id: "prompt-10", text: "誰最會在迷路的時候，還讓大家笑得出來？" },
  { id: "prompt-11", text: "這趟旅行讓你想起某次舊旅行的哪個畫面？" },
  { id: "prompt-12", text: "如果我們是一部公路片，片名會叫什麼？" },
  { id: "prompt-13", text: "今天誰說的一句話，你想記下來？" },
  { id: "prompt-14", text: "行李裡有什麼是其實可以不帶、你還是帶來了的？" },
  { id: "prompt-15", text: "如果要為這趟旅行選一首背景音樂，你腦中會先浮出哪一首？" },
  { id: "prompt-16", text: "路上你最想問當地人的一個問題是什麼？" },
  { id: "prompt-17", text: "誰最會把「再五分鐘」變成「再一個景點」？" },
  { id: "prompt-18", text: "如果明天早餐只能點一樣，你會點什麼，又想跟誰分？" },
  { id: "prompt-19", text: "這趟旅行裡，哪個片刻讓你覺得「來對了」？" },
  { id: "prompt-20", text: "如果可以跟某位旅伴交換一天的角色，你想試試誰的視角？" },
  { id: "prompt-21", text: "你在這趟旅行學到的、最小但最想記住的一件事是什麼？" },
  { id: "prompt-22", text: "如果回程的車上只能聊一個話題，你希望是什麼？" },
  { id: "prompt-23", text: "誰的拍照角度，最讓你想把自己也放進畫面裡？" },
  { id: "prompt-24", text: "如果我們腳下這個地方會說話，它會先跟我們說哪一句？" },
  { id: "prompt-25", text: "旅行結束後，你最想傳給沒一起來的人的，是哪一個畫面？" },
  { id: "prompt-26", text: "如果要用三種顏色形容今天，你會選哪三色？" },
  { id: "prompt-27", text: "路上有沒有一個陌生人的小善意，你還記得？" },
  { id: "prompt-28", text: "如果要辦一場小小的旅途回顧，第一件展品會是什麼？" },
  { id: "prompt-29", text: "誰最會在大家累的時候，丟出剛剛好的一句話？" },
  { id: "prompt-30", text: "這趟旅行，你最想對自己說的一句鼓勵是什麼？" },
  { id: "prompt-31", text: "如果可以把今天的天氣裝進罐子，你會在什麼時候打開？" },
  { id: "prompt-32", text: "有沒有一道菜或一口零食，讓整桌突然安靜了三秒？" },
  { id: "prompt-33", text: "如果旅程有一個隱藏關卡，你覺得我們已經通過了嗎？" },
  { id: "prompt-34", text: "你會把這趟旅行的哪一段，推薦給未來的自己？" },
  { id: "prompt-35", text: "今晚睡前，你希望腦中留下的最後一個畫面是什麼？" },
  { id: "prompt-36", text: "如果要在地圖上為今天釘一顆星星，你會釘在哪裡？為什麼是那裡？" },
];

/** Light, kind, doable mini-challenges. Never humiliating or forced. */
export const vibeDeck = [
  { id: "vibe-01", tag: "稱讚", text: "對左邊的旅伴說一個具體的讚美，關於這趟旅行裡他做過的一件小事。" },
  { id: "vibe-02", tag: "拍照", text: "拍一張「只有我們會懂」的小細節（招牌、影子、杯子、路牌都可以），拿給大家看。不用拍人。" },
  { id: "vibe-03", tag: "比畫", text: "用十秒、不說話，比出今天看到的一個路標或店招。" },
  { id: "vibe-04", tag: "分享", text: "分享一個這段路上的小知識。若一時想不到，可以說「我等一下查」，查到再講也算完成。" },
  { id: "vibe-05", tag: "合照", text: "大家一起擺一個「我們正在旅行」的輕鬆姿勢，維持三秒。不好看也完全正確。" },
  { id: "vibe-06", tag: "聲音", text: "用三種聲音，重現今天的一段路。例如腳步、車門、風。" },
  { id: "vibe-07", tag: "觀察", text: "指出眼前一個你覺得好看的顏色，說給大家聽。" },
  { id: "vibe-08", tag: "命名", text: "給這趟旅行取一個「今天限定」的暱稱。" },
  { id: "vibe-09", tag: "導遊", text: "用三十秒，像導遊一樣介紹我們的下一站。就算下一站是回飯店。" },
  { id: "vibe-10", tag: "感謝", text: "跟一位旅伴擊掌，或隔空擊掌，並說出你感謝他的一件小事。" },
  { id: "vibe-11", tag: "日記", text: "用一句話形容今天的天氣，像寫進旅行日記那樣，然後念出來。" },
  { id: "vibe-12", tag: "吉祥物", text: "從身邊找一件可以當旅途吉祥物的小東西，舉起來介紹它的性格。" },
  { id: "vibe-13", tag: "稱號", text: "給右邊的旅伴一個好聽、具體、不損人的旅行稱號。" },
  { id: "vibe-14", tag: "睜眼", text: "大家一起閉眼五秒。睜開後，指出你第一眼看到的好玩東西。" },
  { id: "vibe-15", tag: "改詞", text: "把一句熟悉的歌詞或廣告，改成適合我們現在這個地方的話。" },
  { id: "vibe-16", tag: "敬一杯", text: "說出你今天喝過、或正想喝的一杯東西，向大家敬一下。想像中的杯子也算。" },
  { id: "vibe-17", tag: "姿勢", text: "擺一個「迷路但很開心」的姿勢，維持三秒。不想入鏡的人，伸出一隻手就好。" },
  { id: "vibe-18", tag: "小事", text: "說一個你以為大家不知道的、很小的旅途喜好。" },
  { id: "vibe-19", tag: "猜聲音", text: "用手機錄三秒環境音，放給大家猜是哪裡。猜錯也鼓掌。" },
  { id: "vibe-20", tag: "信任", text: "選一位旅伴，說完這句：如果這段路交給你帶，我會放心，因為……" },
  { id: "vibe-21", tag: "齊聲", text: "一起數到三，同時說出此刻最想吃的東西。" },
  { id: "vibe-22", tag: "三個詞", text: "用三個詞總結今天，其中一個要有一點好笑。" },
  { id: "vibe-23", tag: "許願", text: "對空氣中的旅途小精靈許一個很小的願，說出來。" },
  { id: "vibe-24", tag: "交通", text: "模仿一種我們今天坐過、或看見的交通工具聲音，讓大家猜。" },
];

/**
 * Scoring cards. Stakes stay playful: compliments, preferences, a tiny treat.
 * Scores never drop below zero.
 */
export const scoreDeck = [
  {
    id: "score-01",
    type: "vote",
    kicker: "投票",
    honor: "本輪旅伴",
    text: "這趟誰最會把地圖看成抽象畫，卻還是把大家帶到了？",
  },
  {
    id: "score-02",
    type: "vote",
    kicker: "投票",
    honor: "加菜賞",
    text: "誰最會在餐廳多點一道「我們分著吃」？",
  },
  {
    id: "score-03",
    type: "vote",
    kicker: "投票",
    honor: "節奏大師",
    text: "誰的節奏最好，知道什麼時候該停下來坐著？",
  },
  {
    id: "score-04",
    type: "vote",
    kicker: "投票",
    honor: "找角落的人",
    text: "誰最會發現路邊不起眼、但很好拍的角落？",
  },
  {
    id: "score-05",
    type: "vote",
    kicker: "投票",
    honor: "再繞一圈",
    text: "誰最可能在回程前還說「再繞一圈就好」？",
  },
  {
    id: "score-06",
    type: "vote",
    kicker: "投票",
    honor: "笑容傳染",
    text: "誰今天的笑容最有傳染力？",
  },
  {
    id: "score-07",
    type: "vote",
    kicker: "投票",
    honor: "餓了就找",
    text: "誰最會在大家餓的時候，精準提出要吃什麼？",
  },
  {
    id: "score-08",
    type: "vote",
    kicker: "投票",
    honor: "隱藏導遊",
    text: "誰最像這趟旅行的隱藏導遊？",
  },
  {
    id: "score-09",
    type: "vote",
    kicker: "投票",
    honor: "等車詩人",
    text: "誰最會把等車、等餐的時間變成聊天？",
  },
  {
    id: "score-10",
    type: "vote",
    kicker: "投票",
    honor: "旅途獎盃",
    text: "誰今天最值得一枚小小的旅途獎盃？",
  },
  {
    id: "score-11",
    type: "choice",
    kicker: "選擇",
    text: "如果現在立刻加一站，你比較想去哪裡？",
    options: [
      { id: "a", label: "海邊或河岸" },
      { id: "b", label: "甜點店" },
      { id: "c", label: "觀景的地方" },
      { id: "d", label: "回飯店躺一下" },
    ],
  },
  {
    id: "score-12",
    type: "choice",
    kicker: "選擇",
    text: "這一刻的旅行心情，最接近哪一個？",
    options: [
      { id: "a", label: "很醒" },
      { id: "b", label: "有點餓" },
      { id: "c", label: "剛剛好" },
      { id: "d", label: "還想再走一段" },
    ],
  },
  {
    id: "score-13",
    type: "choice",
    kicker: "選擇",
    text: "回程的車上，你想先做什麼？",
    options: [
      { id: "a", label: "睡一下" },
      { id: "b", label: "看今天的照片" },
      { id: "c", label: "繼續聊天" },
      { id: "d", label: "安靜看風景" },
    ],
  },
  {
    id: "score-14",
    type: "choice",
    kicker: "選擇",
    text: "如果用一種天氣形容我們這群人？",
    options: [
      { id: "a", label: "晴天" },
      { id: "b", label: "舒服的風" },
      { id: "c", label: "忽然的陣雨" },
      { id: "d", label: "傍晚的金色" },
    ],
  },
  {
    id: "score-15",
    type: "honor",
    kicker: "獎勵",
    text: "說一件今天你覺得自己做得很好的小事。說完，收下 3 分。",
  },
  {
    id: "score-16",
    type: "honor",
    kicker: "獎勵",
    text: "接受旅伴們的鼓掌——心裡鼓掌也算。然後收下 3 分。",
  },
  {
    id: "score-17",
    type: "treat",
    kicker: "小懲",
    text: "請大家喝一杯想像中的飲料。你減 1 分（不會低於 0），其他旅伴各加 1 分。",
  },
  {
    id: "score-18",
    type: "treat",
    kicker: "小懲",
    text: "用導遊的語氣，花三十秒介紹我們現在站的地方。介紹完，你減 1 分（不會低於 0），在場旅伴各加 1 分。",
  },
];
